[tool.bumpversion]
current_version = "0.1.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
commit = true
tag = true
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "Scripts/generate_project.rb"
search = 'settings["MARKETING_VERSION"] = "{current_version}"'
replace = 'settings["MARKETING_VERSION"] = "{new_version}"'

[[tool.bumpversion.files]]
filename = "Stow.xcodeproj/project.pbxproj"
search = "MARKETING_VERSION = {current_version};"
replace = "MARKETING_VERSION = {new_version};"
